version: '3'
services:
  access-gate:
    build: .
    image: dougrich/access-gate
    environment:
    - ACCESS_CODE=secret-muffin
    - PROXY_HOST=http://example.com
    - PROXY_DEST=http://nginx
    ports:
    - '8080:80'
  nginx:
    image: nginx
